### ISSUE TITLE
mysql failing push images

### ISSUE THREAD

**Issue by bparees** [openshift/mysql#120]
I lost track of the other issue, but mysql is still causing flakes in the push job:
https://ci.openshift.redhat.com/jenkins/view/Image%20Verification/job/push_images/18216/console

@mnagy @mfojtik 
(if the other issue is still open, feel free to close this one).

**Comment by mfojtik** [comment]
@bparees push_images seems to work fine now.

**Comment by bparees** [comment]
i'm not so sure, but i'll reopen it the next time we rebuild all the images and it fails again :)

**Comment by mfojtik** [comment]
i'll bookmark this issue to know the weather on mysql push front :-)

On Fri, Feb 12, 2016 at 3:41 PM, Ben Parees <notifications@github.com>
wrote:

> i'm not so sure, but i'll reopen it the next time we rebuild all the
> images and it fails again :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/mysql/issues/120#issuecomment-183355843>.
>



-- 
-----------------------------------------------
Michal Fojtik <mi@mifo.sk <mfojtik@mifo.sk>>
Red Hat OpenShift, Engineering
