### ISSUE TITLE
mysql 5.6 keep restarting

### ISSUE THREAD

**Issue by mfojtik** [openshift/mysql#121]
I see the mysql container restarting every 10-20seconds. I see this exit code in docker ps:

```console
36b961f1d7f2        docker.io/centos/mysql-56-centos7@sha256:6803ba424dbebce4ea577882e6e37ecf368892cd4804162a7c90f7ef307bbdc1                     "container-entrypoint"   5 minutes ago       Exited (137) 3 minutes ago
```

There is **nothing** in container logs (at least nothing that smells). The mysql process just exit. From the docs, the 137 code means: `No more records (read after end of file)`... In some case, the 137 in docker means "container killed".

@mnagy can you please have a look at this? It is pretty annoying, because the DB get up and keep running for ~10s and then container restart, cutting all connections... then it come back again... annoying :/

**Comment by mfojtik** [comment]
@bparees this can easily sneak from being captured by testing as we never run mysql longer then couple seconds... 

This might be:

1) mysql internal problem
2) some misconfiguration
3) resources problem?

**Comment by bparees** [comment]
does this always happen?  i don't think i've ever observed it.
```
$ oc get pods
NAME                        READY     STATUS      RESTARTS   AGE
database-1-odoem            1/1       Running     0          22m
```

```
$ oc describe pod database-1-odoem
Name:				database-1-odoem
Namespace:			p2
Image(s):			centos/mysql-56-centos7:latest
```

**Comment by mfojtik** [comment]
@bparees i'm running openshift in digitalocean (origin / latest images). I think the issue is the memory or resources, which is OK, but there is nothing in mysql log that tells me mysql need more space/memory. Just keep restarting.

**Comment by ajdevries** [comment]
Are you using this template https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/files/examples/v1.2/db-templates/mysql-persistent-template.json. I think there is a bug in the readiness probe. If you remove the quotes around `$MYSQL_PASSWORD` the container gets started. This is also logged in the Event log of the Pod.

**Comment by bparees** [comment]
this issue pre-dates the update that broke the readiness probe (ironically @mfojtik is the one who added the broken readiness probe :) ).

anyway the readiness probe issue is being fixed (also by @mfojtik) here: https://github.com/openshift/origin/pull/8208

but the original issue presumably still remains (though it would be nice if @mfojtik could confirm it's still a problem for him)

**Comment by ajdevries** [comment]
Okay... sorry didn't know... just found out this one. Are these fixes also applied to the ansible repo. For the people who are installing thing manually ;-)

**Comment by bparees** [comment]
@ajdevries they aren't applied anywhere yet(PR hasn't merged, but should soon), but I think @sdodson will end up moving them to the ansible repo in the near future.

**Comment by ajdevries** [comment]
Great... Thanks for your quick response.

**Comment by mfojtik** [comment]
I think this issue was related to small memory on my node, but I would still expect mysql to crash 'nicely' ;-)
