### ISSUE TITLE
Strange differences in scripts for 5.5 and 5.6

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/mysql#140]
I'm trying out the replication example, and first thing I did was compare the source for the two images 5.5 and 5.6.

The scripts `mysqld-master`, `mysqld-slave`, `run-mysqld`, `run-mysqld-master`, `run-mysqld-slave` differ in apparently unnecessary and strange ways between 5.5 and 5.6.

Using a tool like `meld` to compare the dirs 5.5 and 5.6 reveals what I mean:

![image](https://cloud.githubusercontent.com/assets/88819/15316920/74ae8386-1c1f-11e6-8385-de10b5c20eb4.png)

![image](https://cloud.githubusercontent.com/assets/88819/15316978/c415f670-1c1f-11e6-8c89-e10a9c308016.png)

I'm confused by the diffs.

- Why does 5.5 export `MYSQL_RUNNING_AS_MASTER=1` and 5.6 doesn't?
- Why `log_volume_info $MYSQL_DATADIR` lines appear in different places (5.5 != 5.6)?
- Why does the `GRANT REPLICATION` statements differ?
- Why does 5.5 has some extra code related to binlog that 5.6 doesn't have?

**Comment by rhcarvalho** [comment]
Trying to answer my own questions...

> Why does the GRANT REPLICATION statements differ?
> Why does 5.5 has some extra code related to binlog that 5.6 doesn't have?

Possibly the two questions are related.
According to #64, it is possible to use a better replication approach in 5.6.

@hhorak do you know if it is possible to use the same better approach in 5.5?


> Why log_volume_info $MYSQL_DATADIR lines appear in different places (5.5 != 5.6)?

The difference was introduced in #119. @mnagy could you shed some light here? Are those differences necessary?

**Comment by mnagy** [comment]
@rhcarvalho Replication is very different and cannot be reconciled, unfortunately. We can discus later on how to keep these differences in a deduplicated base.

The log_volume_info calls are an honest mistake, created PR #141 to fix these.

**Comment by hhorak** [comment]
> @hhorak do you know if it is possible to use the same better approach in 5.5?

No, GTID was added in 5.6 only, for 5.5 we need to use the approach with `replication` table.

**Comment by hhorak** [comment]
> Why does 5.5 export MYSQL_RUNNING_AS_MASTER=1 and 5.6 doesn't?

There is nothing special needed to be done when using GTID, however in 5.5 we need to know where the start to replicate from, so that's why there is the `replication` table used. We need to do it only on master, so that's why there is `MYSQL_RUNNING_AS_MASTER`.

**Comment by rhcarvalho** [comment]
@hhorak thanks for the answers. Closing this assuming @mnagy PR is merging soon.

The differences left are only related to the different approaches of replication.
