### ISSUE TITLE
Need to verify that all database images works fine with NFS volume in OpenShift

### ISSUE THREAD

**Issue by mfojtik** [openshift/mysql#41]
We have to make sure that **all** our database images works well with the NFS volume mount inside OpenShift.

@mnagy you have to sync with @markturansky about how to setup the Volume for MySQL pod to use the NFS server you have to run in Vagrant box. Then you should deploy the MySQL, make it create database and insert some records. Then you should re-deploy MySQL (you can just change some random Env var in PodSpec) and verify that the data you created are persisted. (you will need set ConfigChange trigger for that)

**Comment by mfojtik** [comment]
CC @bparees @danmcp

**Comment by mfojtik** [comment]
@hhorak FYI

**Comment by hhorak** [comment]
Hm, unless you try to run two containers with the same data mounted, it shouldn't be problem. At least I'm not aware of any.

**Comment by mfojtik** [comment]
@hhorak yeah, not the case here... this is more about verifying that containers with data mounted will just pickup the existing data and continue to work (or they break). So far we were not testing this.
Also having an data stored on NFS volume might reveal some problems as well (for example etcd don't like having data on NFS)

**Comment by praiskup** [comment]
Michal, the NFS mount is done on host and then it is "volume mounted" into
container, am I right?  Can you send us the link to etcd issue please?

Thanks, Pavel

**Comment by mfojtik** [comment]
@praiskup

```console
2015/05/29 11:49:45 etcdserver: datadir is valid for the 2.0.1 format
2015/05/29 11:49:45 etcdserver: name = openshift.local
2015/05/29 11:49:45 etcdserver: data dir = openshift.local.etcd
2015/05/29 11:49:45 etcdserver: member dir = openshift.local.etcd/member
2015/05/29 11:49:45 etcdserver: heartbeat = 100ms
2015/05/29 11:49:45 etcdserver: election = 1000ms
2015/05/29 11:49:45 etcdserver: snapshot count = 0
2015/05/29 11:49:45 etcdserver: advertise client URLs = https://192.168.121.187:4001
2015/05/29 11:49:45 etcdserver: initial advertise peer URLs = https://192.168.121.187:7001
2015/05/29 11:49:45 etcdserver: initial cluster = openshift.local=https://192.168.121.187:7001
2015/05/29 11:49:46 etcdserver: create wal error: no locks available
```

(this happens when I start tell etcd to store data in NFS volume I have mounted to my vagrant box...)
I haven't tried this in Kubernetes (yes) but I think same issue will exists there.

**Comment by mnagy** [comment]
Just tried creating a NFS mount on my AWS vagrant machine. Using the sample-app, I resized the DB replication controller to 0 and back to 1 and the database was persistent, so it seems that MySQL image works fine.

**Comment by markturansky** [comment]
@mnagy what kind of volume did you use?   EBS volume in a pod or EBS as a persistent volume?

**Comment by mnagy** [comment]
@markturansky I did not use EBS, I just created a directory on my vagrant box and exported it via NFS. I then added a NFS volume to the database RC, following @mfojtik's instructions.

Any other use case I should test?

**Comment by markturansky** [comment]
no, that's good as far as creating images is concerned.   If the mount work for NFS as Volume it should work for NFS as PersistentVolume.  It's all the same mounting logic.

**Comment by mnagy** [comment]
@danmcp or @mfojtik: do we want to have some example in place or something to demonstrate the persistence? Any suggestions?

I'm going to try to fix the ruby hello world for now, it can't handle the DB reconnection.

**Comment by danmcp** [comment]
@mnagy 1st priority is the OOTB templates so be setup to work with NFS.

It would be good for every other sample we have to have it as an option.  Or instructions on how to do it in the readme.

**Comment by mnagy** [comment]
FYI, https://github.com/openshift/origin/pull/2644

Got MySQL and PostgreSQL working for now, will tackle Mongo tomorrow.

**Comment by mnagy** [comment]
MongoDB works as well.

**Comment by mnagy** [comment]
Closing this, since everything was verified.
