### ISSUE TITLE
Make my.cnf configurable

### ISSUE THREAD

**Issue by mfojtik** [openshift/mysql#7]
The my.cnf should be a template where we do env substitution to provide basic customization for the mysql server to users. For beginning we should have same set of ENV vars as we had in v2. Consider this for future.

**Comment by mnagy** [comment]
Would it be possible to instead use the /etc/my.cnf.d/ dir mechanism?

**Comment by mfojtik** [comment]
@mnagy it will be supplementary but the first focus would be on having list of environment variables that maps to the same vars in v2. The 'my.cnf' will be then processed as ERB template and the values will be substituted.

Example:

```erb
<%= ENV['MYSQL_TIMEZONE'] ? "default-time-zone = '#{ENV['MYSQL_TIMEZONE']}'" : '' %>
```

For more examples look at: https://github.com/openshift/origin-server/blob/master/cartridges/openshift-origin-cartridge-mysql/conf/my.cnf.erb

**Comment by bparees** [comment]
Keep in mind that we shouldn't necessarily be beholden to continuing to use erb since we're not as ruby based as we used to be.  (Though copying the templates straight from v2 has some appeal)

**Comment by mnagy** [comment]
This is old, closing.
