### ISSUE TITLE
Allow not to create database during start

### ISSUE THREAD

**Issue by hhorak** [openshift/mysql#96]
The use case I'd like to support is when somebody migrates database from one machine to this container. Then the user typically has an SQL dump and wants to do just this:

* run the container without anything being initialized
* import data as root

The solution may be to have `MYSQL_DATABASE`, `MYSQL_USER` and `MYSQL_PASSWORD` optional when `MYSQL_ROOT_PASSWORD` is set.

FYI @mnagy

**Comment by mnagy** [comment]
+1 for the proposed solution

**Comment by bparees** [comment]
sounds reasonable.

**Comment by hhorak** [comment]
Implemented by makeing `MYSQL_USER`, `MYSQL_PASSWORD` and `MYSQL_DATABASE` optional.
